### ISSUE TITLE
Add a new method apart from OpenAI for retrieving information from a resume

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/resume_scanner#1]
Add a new folder which contains a new method apart from OpenAI for resume scanning using LLMs preferably use `HuggingFace` or `Llama3.2` provided by `Groq` for the same and create a folder for your code with the relevant name.

**Comment by Sohammhatre10** [comment]
Add support for 

- [ ] Llama 3.2
- [ ] Mixtral 7182b
- [ ] Gemini 
- [ ] Anthropic Claude
- [ ] ChatOllama's base model
- [ ] Huggingface Open Source LLMs

**Comment by PranavBhatP** [comment]
Hey, I can try adding support with ChatOllama. Should I add this as an issue?

**Comment by Sohammhatre10** [comment]
Sure @PranavBhatP please use `ChatOllama` from `langchain` as Ollama locally is completed.
