### ISSUE TITLE
Adding Contribution Rules

### ISSUE THREAD

**Issue by ainacodes** [Sohammhatre10/resume_scanner#21]
Hi @Sohammhatre10,
Can I add the Contribution Rules in this repo?
And why do you have requirements.txt in every separate folder? Can we just combine them?

Thank you

**Comment by Sohammhatre10** [comment]
Sure you may go ahead with this, thanks!

**Comment by Cgarg9** [comment]
can i do this if not worked on till now?

**Comment by Sohammhatre10** [comment]
@Cgarg9 this has been addressed here https://github.com/Sohammhatre10/resume_scanner/pull/25
