### ISSUE TITLE
Gemma using Groq API

### ISSUE THREAD

**Issue by Cgarg9** [Sohammhatre10/resume_scanner#24]
I would like to add functionality to read pdf using Gemma

**Comment by Sohammhatre10** [comment]
This issue has already been completed by using the generic Groq API using Gemma as the base model here https://github.com/Sohammhatre10/resume_scanner/pull/11 or here https://github.com/Sohammhatre10/resume_scanner/pull/20

**Comment by Cgarg9** [comment]
@Sohammhatre10  #11 is using Llama and #20 is using gemini. Please recheck and if available assign this to me
