### ISSUE TITLE
Resume creation using Groq Llama API

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/resume_scanner#29]
Use Groq's API for calling Llama 3.2 and create a resume using the old one.
You may refer to this https://github.com/Sohammhatre10/resume_scanner/blob/main/GroqLlamaResumeScanner/resume_scanner.py

**Comment by agrawal-sneha** [comment]
please assign to it to me @Sohammhatre10

**Comment by Sohammhatre10** [comment]
Sure @agrawal-sneha
