### ISSUE TITLE
Add functionality for the usage of Llama 3.2

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/resume_scanner#3]
Add functionality for the usage of `Llama 3.2` for resume scanning instead of `Open Ai's GPT-4o`

**Comment by INEcodes** [comment]
Can we do it using the llama_cpp module?
Should we make a new file or add a function to the existing file?

**Comment by Shaunak-Gupta-dev** [comment]
Hey @Sohammhatre10 , I'd like to take this up. Could you please assign this issue to me?

**Comment by Sohammhatre10** [comment]
@INEcodes yup you can, just make sure you create a new folder with `llamacpp` as the title before raising the PR, this will make it more organised.

**Comment by Sohammhatre10** [comment]
@Shaunak-Gupta-dev you may try using the Groq-dev cloud for the same functionality I'll make sure that `llamacpp` and `GroqLlama` both folders are merged.

**Comment by Sohammhatre10** [comment]
@Shaunak-Gupta-dev please add a comment on https://github.com/Sohammhatre10/resume_scanner/issues/6 as your PR addresses that issue. Will be assigning that issue to you.

**Comment by Shaunak-Gupta-dev** [comment]
@Sohammhatre10, I apologize for the earlier mistake. I mistakenly named my previous PR as "Gemini" integration, but it was actually for integrating Llama using the Groq API. I have now raised a new PR with the correct name.

Please consider reviewing the updated PR, and I’m sorry for the confusion.

**Comment by Sohammhatre10** [comment]
@Shaunak-Gupta-dev no problem, Thanks for the contribution!
