### ISSUE TITLE
Resume creation for Groq's Mixtral API

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/resume_scanner#30]
Use Groq's API for calling Llama 3.2 and create a resume using the old one.
You may refer to this https://github.com/Sohammhatre10/resume_scanner/blob/main/GroqMixtralResumeScanner/resume_scanner.py

**Comment by agrawal-sneha** [comment]
please assign it to me @Sohammhatre10

**Comment by Sohammhatre10** [comment]
Sure @agrawal-sneha
