### ISSUE TITLE
Add functionality for Google's Gemini

### ISSUE THREAD

**Issue by Sohammhatre10** [Sohammhatre10/resume_scanner#6]
Add functionality for Google's Gemini using Groq API in the folder `GeminiResumeScan`

**Comment by Shaunak-Gupta-dev** [comment]
Hey @Sohammhatre10 , I'd like to take this up. Could you please assign this issue to me?

**Comment by Kabiirk** [comment]
Hi @Sohammhatre10 , 

I'd like to work on this can you please assign this to me ? 

From what I understand, based on `LlamaCppResumeScan/llama_cpp.py` and `OpenAIResumeScanner/resume_scanner.py`, we can leverage the existing [API infrastructure](https://ai.google.dev/pricing#1_5flash) setup by Gemini. Let me know if that works for you.

**Comment by Ncode-93** [comment]
Hey @Sohammhatre10   I can work on this issue.

**Comment by Sohammhatre10** [comment]
Will assign this to @Kabiirk just for fcfs. 
@Ncode-93 will assign you a different issue.
